export const LOGIN_LOAD_INITIAL_DATA = 'LOGIN_LOAD_INITIAL_DATA';
export const LOGIN_INGRESAR = 'LOGIN_INGRESAR';
export const LOGIN_SET_USUARIO_LOGUEADO = 'LOGIN_SET_USUARIO_LOGUEADO';
export const LOGIN_SET_DATA_USUARIOS = 'LOGIN_SET_DATA_USUARIOS';