export const ADMINISTRADOR_SET_CURRENT_USER = 'ADMINISTRADOR_SET_CURRENT_USER';
export const ADMINISTRADOR_ELIMINAR_USER = 'ADMINISTRADOR_ELIMINAR_USER';
export const ADMINISTRADOR_OPEN_MODAL = 'ADMINISTRADOR_OPEN_MODAL';
export const ADMINISTRADOR_SET_USERS = 'ADMINISTRADOR_SET_USERS';
export const ADMINISTRADOR_SET_IS_EDIT = 'ADMINISTRADOR_SET_IS_EDIT';
export const ADMINISTRADOR_CREAR_USUARIO = 'ADMINISTRADOR_CREAR_USUARIO';